% Produced by CVXGEN, 2022-12-01 16:21:35 -0500.
% CVXGEN is Copyright (C) 2006-2017 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2017 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
A = params.A;
B = params.B;
Q = params.Q;
R = params.R;
d_k = params.d_k;
delta_vcmd_max = params.delta_vcmd_max;
delta_vcmd_min = params.delta_vcmd_min;
deltav_max = params.deltav_max;
deltav_min = params.deltav_min;
v_cmd_last = params.v_cmd_last;
if isfield(params, 'v_ref_1')
  v_ref_1 = params.v_ref_1;
elseif isfield(params, 'v_ref')
  v_ref_1 = params.v_ref{1};
else
  error 'could not find v_ref_1'
end
if isfield(params, 'v_ref_2')
  v_ref_2 = params.v_ref_2;
elseif isfield(params, 'v_ref')
  v_ref_2 = params.v_ref{2};
else
  error 'could not find v_ref_2'
end
if isfield(params, 'v_ref_3')
  v_ref_3 = params.v_ref_3;
elseif isfield(params, 'v_ref')
  v_ref_3 = params.v_ref{3};
else
  error 'could not find v_ref_3'
end
if isfield(params, 'v_ref_4')
  v_ref_4 = params.v_ref_4;
elseif isfield(params, 'v_ref')
  v_ref_4 = params.v_ref{4};
else
  error 'could not find v_ref_4'
end
if isfield(params, 'v_ref_5')
  v_ref_5 = params.v_ref_5;
elseif isfield(params, 'v_ref')
  v_ref_5 = params.v_ref{5};
else
  error 'could not find v_ref_5'
end
if isfield(params, 'v_ref_6')
  v_ref_6 = params.v_ref_6;
elseif isfield(params, 'v_ref')
  v_ref_6 = params.v_ref{6};
else
  error 'could not find v_ref_6'
end
if isfield(params, 'v_ref_7')
  v_ref_7 = params.v_ref_7;
elseif isfield(params, 'v_ref')
  v_ref_7 = params.v_ref{7};
else
  error 'could not find v_ref_7'
end
if isfield(params, 'v_ref_8')
  v_ref_8 = params.v_ref_8;
elseif isfield(params, 'v_ref')
  v_ref_8 = params.v_ref{8};
else
  error 'could not find v_ref_8'
end
if isfield(params, 'v_ref_9')
  v_ref_9 = params.v_ref_9;
elseif isfield(params, 'v_ref')
  v_ref_9 = params.v_ref{9};
else
  error 'could not find v_ref_9'
end
if isfield(params, 'v_ref_10')
  v_ref_10 = params.v_ref_10;
elseif isfield(params, 'v_ref')
  v_ref_10 = params.v_ref{10};
else
  error 'could not find v_ref_10'
end
if isfield(params, 'v_ref_11')
  v_ref_11 = params.v_ref_11;
elseif isfield(params, 'v_ref')
  v_ref_11 = params.v_ref{11};
else
  error 'could not find v_ref_11'
end
if isfield(params, 'v_ref_12')
  v_ref_12 = params.v_ref_12;
elseif isfield(params, 'v_ref')
  v_ref_12 = params.v_ref{12};
else
  error 'could not find v_ref_12'
end
if isfield(params, 'v_ref_13')
  v_ref_13 = params.v_ref_13;
elseif isfield(params, 'v_ref')
  v_ref_13 = params.v_ref{13};
else
  error 'could not find v_ref_13'
end
if isfield(params, 'v_ref_14')
  v_ref_14 = params.v_ref_14;
elseif isfield(params, 'v_ref')
  v_ref_14 = params.v_ref{14};
else
  error 'could not find v_ref_14'
end
if isfield(params, 'v_ref_15')
  v_ref_15 = params.v_ref_15;
elseif isfield(params, 'v_ref')
  v_ref_15 = params.v_ref{15};
else
  error 'could not find v_ref_15'
end
if isfield(params, 'v_ref_16')
  v_ref_16 = params.v_ref_16;
elseif isfield(params, 'v_ref')
  v_ref_16 = params.v_ref{16};
else
  error 'could not find v_ref_16'
end
if isfield(params, 'v_ref_17')
  v_ref_17 = params.v_ref_17;
elseif isfield(params, 'v_ref')
  v_ref_17 = params.v_ref{17};
else
  error 'could not find v_ref_17'
end
if isfield(params, 'v_ref_18')
  v_ref_18 = params.v_ref_18;
elseif isfield(params, 'v_ref')
  v_ref_18 = params.v_ref{18};
else
  error 'could not find v_ref_18'
end
if isfield(params, 'v_ref_19')
  v_ref_19 = params.v_ref_19;
elseif isfield(params, 'v_ref')
  v_ref_19 = params.v_ref{19};
else
  error 'could not find v_ref_19'
end
if isfield(params, 'v_ref_20')
  v_ref_20 = params.v_ref_20;
elseif isfield(params, 'v_ref')
  v_ref_20 = params.v_ref{20};
else
  error 'could not find v_ref_20'
end
if isfield(params, 'v_ref_21')
  v_ref_21 = params.v_ref_21;
elseif isfield(params, 'v_ref')
  v_ref_21 = params.v_ref{21};
else
  error 'could not find v_ref_21'
end
vcmd_max = params.vcmd_max;
vcmd_min = params.vcmd_min;
vmax = params.vmax;
vmin = params.vmin;
x_0 = params.x_0;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable u_0;
  variable x_1;
  variable x_2;
  variable x_3;
  variable x_4;
  variable x_5;
  variable x_6;
  variable x_7;
  variable x_8;
  variable x_9;
  variable x_10;
  variable x_11;
  variable x_12;
  variable x_13;
  variable x_14;
  variable x_15;
  variable x_16;
  variable x_17;
  variable x_18;
  variable x_19;
  variable x_20;
  variable x_21;
  variable u_1;
  variable u_2;
  variable u_3;
  variable u_4;
  variable u_5;
  variable u_6;
  variable u_7;
  variable u_8;
  variable u_9;
  variable u_10;
  variable u_11;
  variable u_12;
  variable u_13;
  variable u_14;
  variable u_15;
  variable u_16;
  variable u_17;
  variable u_18;
  variable u_19;
  variable u_20;

  minimize(quad_form(u_0, R) + quad_form(x_1 - v_ref_1, Q) + quad_form(x_2 - v_ref_2, Q) + quad_form(x_3 - v_ref_3, Q) + quad_form(x_4 - v_ref_4, Q) + quad_form(x_5 - v_ref_5, Q) + quad_form(x_6 - v_ref_6, Q) + quad_form(x_7 - v_ref_7, Q) + quad_form(x_8 - v_ref_8, Q) + quad_form(x_9 - v_ref_9, Q) + quad_form(x_10 - v_ref_10, Q) + quad_form(x_11 - v_ref_11, Q) + quad_form(x_12 - v_ref_12, Q) + quad_form(x_13 - v_ref_13, Q) + quad_form(x_14 - v_ref_14, Q) + quad_form(x_15 - v_ref_15, Q) + quad_form(x_16 - v_ref_16, Q) + quad_form(x_17 - v_ref_17, Q) + quad_form(x_18 - v_ref_18, Q) + quad_form(x_19 - v_ref_19, Q) + quad_form(x_20 - v_ref_20, Q) + quad_form(x_21 - v_ref_21, Q));
  subject to
    x_1 == A*x_0 + B*u_0 + d_k;
    x_2 == A*x_1 + B*u_1 + d_k;
    x_3 == A*x_2 + B*u_2 + d_k;
    x_4 == A*x_3 + B*u_3 + d_k;
    x_5 == A*x_4 + B*u_4 + d_k;
    x_6 == A*x_5 + B*u_5 + d_k;
    x_7 == A*x_6 + B*u_6 + d_k;
    x_8 == A*x_7 + B*u_7 + d_k;
    x_9 == A*x_8 + B*u_8 + d_k;
    x_10 == A*x_9 + B*u_9 + d_k;
    x_11 == A*x_10 + B*u_10 + d_k;
    x_12 == A*x_11 + B*u_11 + d_k;
    x_13 == A*x_12 + B*u_12 + d_k;
    x_14 == A*x_13 + B*u_13 + d_k;
    x_15 == A*x_14 + B*u_14 + d_k;
    x_16 == A*x_15 + B*u_15 + d_k;
    x_17 == A*x_16 + B*u_16 + d_k;
    x_18 == A*x_17 + B*u_17 + d_k;
    x_19 == A*x_18 + B*u_18 + d_k;
    x_20 == A*x_19 + B*u_19 + d_k;
    x_21 == A*x_20 + B*u_20 + d_k;
    vmin <= x_1;
    vmin <= x_2;
    vmin <= x_3;
    vmin <= x_4;
    vmin <= x_5;
    vmin <= x_6;
    vmin <= x_7;
    vmin <= x_8;
    vmin <= x_9;
    vmin <= x_10;
    vmin <= x_11;
    vmin <= x_12;
    vmin <= x_13;
    vmin <= x_14;
    vmin <= x_15;
    vmin <= x_16;
    vmin <= x_17;
    vmin <= x_18;
    vmin <= x_19;
    vmin <= x_20;
    vmin <= x_21;
    x_1 <= vmax;
    x_2 <= vmax;
    x_3 <= vmax;
    x_4 <= vmax;
    x_5 <= vmax;
    x_6 <= vmax;
    x_7 <= vmax;
    x_8 <= vmax;
    x_9 <= vmax;
    x_10 <= vmax;
    x_11 <= vmax;
    x_12 <= vmax;
    x_13 <= vmax;
    x_14 <= vmax;
    x_15 <= vmax;
    x_16 <= vmax;
    x_17 <= vmax;
    x_18 <= vmax;
    x_19 <= vmax;
    x_20 <= vmax;
    x_21 <= vmax;
    deltav_min <= x_1 - x_0;
    deltav_min <= x_2 - x_1;
    deltav_min <= x_3 - x_2;
    deltav_min <= x_4 - x_3;
    deltav_min <= x_5 - x_4;
    deltav_min <= x_6 - x_5;
    deltav_min <= x_7 - x_6;
    deltav_min <= x_8 - x_7;
    deltav_min <= x_9 - x_8;
    deltav_min <= x_10 - x_9;
    deltav_min <= x_11 - x_10;
    deltav_min <= x_12 - x_11;
    deltav_min <= x_13 - x_12;
    deltav_min <= x_14 - x_13;
    deltav_min <= x_15 - x_14;
    deltav_min <= x_16 - x_15;
    deltav_min <= x_17 - x_16;
    deltav_min <= x_18 - x_17;
    deltav_min <= x_19 - x_18;
    deltav_min <= x_20 - x_19;
    deltav_min <= x_21 - x_20;
    x_1 - x_0 <= deltav_max;
    x_2 - x_1 <= deltav_max;
    x_3 - x_2 <= deltav_max;
    x_4 - x_3 <= deltav_max;
    x_5 - x_4 <= deltav_max;
    x_6 - x_5 <= deltav_max;
    x_7 - x_6 <= deltav_max;
    x_8 - x_7 <= deltav_max;
    x_9 - x_8 <= deltav_max;
    x_10 - x_9 <= deltav_max;
    x_11 - x_10 <= deltav_max;
    x_12 - x_11 <= deltav_max;
    x_13 - x_12 <= deltav_max;
    x_14 - x_13 <= deltav_max;
    x_15 - x_14 <= deltav_max;
    x_16 - x_15 <= deltav_max;
    x_17 - x_16 <= deltav_max;
    x_18 - x_17 <= deltav_max;
    x_19 - x_18 <= deltav_max;
    x_20 - x_19 <= deltav_max;
    x_21 - x_20 <= deltav_max;
    delta_vcmd_min <= u_0;
    u_0 <= delta_vcmd_max;
    u_1 == 0;
    u_2 == 0;
    u_3 == 0;
    u_4 == 0;
    u_5 == 0;
    u_6 == 0;
    u_7 == 0;
    u_8 == 0;
    u_9 == 0;
    u_10 == 0;
    u_11 == 0;
    u_12 == 0;
    u_13 == 0;
    u_14 == 0;
    u_15 == 0;
    u_16 == 0;
    u_17 == 0;
    u_18 == 0;
    u_19 == 0;
    u_20 == 0;
    vcmd_min <= v_cmd_last + u_0;
    v_cmd_last + u_0 <= vcmd_max;
cvx_end
vars.u_0 = u_0;
vars.u_1 = u_1;
vars.u{1} = u_1;
vars.u_2 = u_2;
vars.u{2} = u_2;
vars.u_3 = u_3;
vars.u{3} = u_3;
vars.u_4 = u_4;
vars.u{4} = u_4;
vars.u_5 = u_5;
vars.u{5} = u_5;
vars.u_6 = u_6;
vars.u{6} = u_6;
vars.u_7 = u_7;
vars.u{7} = u_7;
vars.u_8 = u_8;
vars.u{8} = u_8;
vars.u_9 = u_9;
vars.u{9} = u_9;
vars.u_10 = u_10;
vars.u{10} = u_10;
vars.u_11 = u_11;
vars.u{11} = u_11;
vars.u_12 = u_12;
vars.u{12} = u_12;
vars.u_13 = u_13;
vars.u{13} = u_13;
vars.u_14 = u_14;
vars.u{14} = u_14;
vars.u_15 = u_15;
vars.u{15} = u_15;
vars.u_16 = u_16;
vars.u{16} = u_16;
vars.u_17 = u_17;
vars.u{17} = u_17;
vars.u_18 = u_18;
vars.u{18} = u_18;
vars.u_19 = u_19;
vars.u{19} = u_19;
vars.u_20 = u_20;
vars.u{20} = u_20;
vars.x_1 = x_1;
vars.x{1} = x_1;
vars.x_2 = x_2;
vars.x{2} = x_2;
vars.x_3 = x_3;
vars.x{3} = x_3;
vars.x_4 = x_4;
vars.x{4} = x_4;
vars.x_5 = x_5;
vars.x{5} = x_5;
vars.x_6 = x_6;
vars.x{6} = x_6;
vars.x_7 = x_7;
vars.x{7} = x_7;
vars.x_8 = x_8;
vars.x{8} = x_8;
vars.x_9 = x_9;
vars.x{9} = x_9;
vars.x_10 = x_10;
vars.x{10} = x_10;
vars.x_11 = x_11;
vars.x{11} = x_11;
vars.x_12 = x_12;
vars.x{12} = x_12;
vars.x_13 = x_13;
vars.x{13} = x_13;
vars.x_14 = x_14;
vars.x{14} = x_14;
vars.x_15 = x_15;
vars.x{15} = x_15;
vars.x_16 = x_16;
vars.x{16} = x_16;
vars.x_17 = x_17;
vars.x{17} = x_17;
vars.x_18 = x_18;
vars.x{18} = x_18;
vars.x_19 = x_19;
vars.x{19} = x_19;
vars.x_20 = x_20;
vars.x{20} = x_20;
vars.x_21 = x_21;
vars.x{21} = x_21;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
