# NOTE: YAML files do not allow tabs. use 2 or 4 spaces for indentation
#
# Reserved TCP/IP port by RealSim: 1337, 1338
# DO NOT use these port when setup clients to RealSim
#
# by minimum, RealSim will run with VISSIM or SUMO. (optional, we can run with IPG, Carla, simulink)
#
# TCP/IP connection port config
#               1337/1338                 ApplicationPort                                   XilPort
#   VISSIM/SUMO ---------> Traffic Layer -----------------> Application Layer (controller) -----------> XIL Clients (simulink models, XIL hardware)


# Global Simulation setup
SimulationSetup:
    
    # Master Switch to turn on/off RealSim interface
    # if turned off, VISSIM will just run without RealSim
    # SUMO needs to run without traci
    EnableRealSim: true
    
    # Whether or not to save verbose log during the simulation. skip log can potentially speed up
    EnableVerboseLog: true
    
    # Simulation end time
    # if NOT specificed, SimulationEndTime will be set to a large value (90000 seconds)
    #--------------------------------------------------
    #SimulationEndTime: 1800
    
    # specify which traffic simulator
    # VISSIM or SUMO
    # default SUMO
    #--------------------------------------------------
    #SelectedTrafficSimulator: 'VISSIM'
    SelectedTrafficSimulator: 'SUMO'

    # default will send all
    # VehicleMessageField: [id, type, speed, acceleration, positionX, positionY, positionZ, heading, color, linkId, laneId, distanceTravel, speedDesired, accelerationDesired]
    # VehicleMessageField: [id, type, speed, acceleration, positionX, positionY, positionZ, linkId, laneId, distanceTravel, speedDesired, accelerationDesired]
    VehicleMessageField: [id, type, speed, acceleration, positionX, positionY, positionZ, heading, color, linkId, laneId, distanceTravel, speedDesired]

    EnableExternalDynamics: true 


# ip and port are server ip and port

# setup Application Layer
ApplicationSetup:
    # turn on/off application layer
    EnableApplicationLayer: false
    
    #--------------------------------------------------
    VehicleSubscription: 
    #-   type: point
    #    attribute: {radius: [500], x: [1523], y: [755.4], z: [0]}
    #    ip: ["127.0.0.1"]
    #    port: [2333]
    #-   type: ego
    #    attribute: {id: ['0_10'], radius: [0]}
    #    ip: ["127.0.0.1"]
    #    port: [2333]
    #-   type: ego
    #    attribute: {id: ['0_11'], radius: [0]}
    #    ip: ["127.0.0.1"]
    #    port: [2333]
    #-   type: ego
    #    attribute: {id: ['0_2'], radius: [0]}
    #    ip: ["192.168.140.42"]
    #    port: [420]
        
# subscription in XilSetup must be subset of ApplicationSetup
XilSetup:
    # enable/disable XIL
    EnableXil: true
    
    # define ego vehicles, which will be simulated in Clients. support: 
    #   1) id of the vehicle (VISSIM id is integer, SUMO id is string). 
    #   for multiple vehicles, give a list, e.g. VISSIM: [1, 2] OR SUMO: ['vehicle_0', 'vehicle_1']
    #   2) use identifier All if need to control all vehicles. e.g., simulate detailed dynamics of all vehicles
    #
    # radius 0 means only the ego vehicle is sent to Xil
    #--------------------------------------------------
    VehicleSubscription: 
    # -   type: ego
        # attribute: {id: ['vehicle_0'], radius: [0]}
        # ip: ["192.168.0.54"]
        # port: [50067]
    # -   type: ego
        # attribute: {id: ['vehicle_0'], radius: [0]}
        # ip: ["127.0.0.1"]
        # port: [420]
    -   type: ego
        attribute: {id: ['0_2'], radius: [0]}
        ip: ["192.168.140.42"]
        port: [420]
    # -   type: ego
        # attribute: {id: ['vehicle_1'], radius: [0]}
        # ip: ["10.12.113.107"]
        # port: [421]  
    # -   type: ego
        # attribute: {id: ['vehicle_0'], radius: [0]}
        # ip: ["127.0.0.1"]
        # port: [420]
    # -   type: ego
        # attribute: {id: ['vehicle_1'], radius: [0]}
        # ip: ["127.0.0.1"]
        # port: [421]    

# flow_0.12 13.4
# flow_1.14 14
# flow_1.15 13.8

    
    
    
    
    
